### ISSUE TITLE
Add this to you icon css class for better adjust icon to center checkbox

### ISSUE THREAD

**Issue by marciocamello** [kartik-v/yii2-checkbox-x#1]
Add this to you icon css class for better adjust icon to center checkbox

```css
.glyphicon {
      left: -1px;
}
```
