### ISSUE TITLE
Add this to you icon css class for better adjust icon to center checkbox

### ISSUE THREAD

**Issue by marciocamello** [kartik-v/yii2-checkbox-x#2]
Add this to you icon css class for better adjust icon to center checkbox

``` css
.cbx .glyphicon {
      left: -1px;
}
```
