### ISSUE TITLE
Checkbox height does not corespond with standard bootstrap form-control height of 34px.

### ISSUE THREAD

**Issue by Lexxtor** [kartik-v/yii2-checkbox-x#6]
With `'size'=>'lg'` heigth = 30px.
With `'size'=>'xl'` heigth = 36px.
And I see no easy way to make it 34px.

Bootstrap css:
```css
.form-control {
    height: 34px;
}
```
